nodejs/node-gyp

- package.json
Which doesn't break the interface and is only going to 1.x to get
normal semver semantics going forward.
> Allow for 1.x npmlog

- lib/rebuild.js
The rebuild command currently ignores additional command line arguments. I think it makes sense to pass these arguments to the configure phase:
````
> node-gyp rebuild -- -I some.gypi
````
> rebuild: forward arguments to configure phase

- addon.gypi
- src/win_delay_load_hook.c
On Windows, when node or io.js attempts to dynamically load a compiled
addon, the compiled addon tries to load node.exe or iojs.exe again -
depending on which import library the module used when it was linked.
This makes it impossible to rename node.exe or iojs.exe, because when
that happens the module can't find its dependencies.
With this patch, a delay-load hook is added to all modules that are
compiled with node-gyp. The delay-load hook ensures that whenever a
module tries to load imports from node.exe/iojs.exe, it'll just refer
back to the process image, thus making it possible to rename the
iojs/node binary.
Bug: iojs/io.js#751
Bug: iojs/io.js#965
Downstream PR: iojs/io.js#1251
> win: allow node.exe/iojs.exe to be renamed

- addon.gypi
Adding `-undefined dynamic_lookup` to all targets makes it impossible to create Xcode projects with node-gyp for gyp files that also include `none` targets. Since `none` targets don't have a framework phase, gyp errors when trying to add the link flag.
In addition, `-undefined dynamic_lookup` should be added as a linker flag, not a link library, so it's now passed in the `OTHER_LDFLAGS` setting.
This also fixes #536.
> Only add "-undefined dynamic_lookup" to loadable_module targets

- src/win_delay_load_hook.c
The declaration of the m variable not on top causes the build to fail on VS2010(C89), Window 7 x64. 
Providing solution based on [stackoverflow answer](http://stackoverflow.com/questions/9903582/error-c2275-illegal-use-of-this-type-as-an-expression).
> move HMODULE m declaration to top

- lib/install.js
If using a manually provided `tarPath` the [content shasums](https://github.com/TooTallNate/node-gyp/blob/master/lib/install.js#L250-L254) aren't [actually computed](https://github.com/TooTallNate/node-gyp/blob/master/lib/install.js#L225) and downloading the remote shasums is a bit of a waste.
This avoids the call, and makes it so you can provide a local tarball with the necessary source files without any external network calls.
> Avoid downloading shasums if using tarPath

- lib/install.js
Instead of just showing Error: getaddrinfo ENOTFOUND
this will show an error message to the user
Turns out the message is quite irritating to users, e.g:
https://github.com/voodootikigod/node-serialport/issues/288
> Show better error message in case of bad network settings

- lib/configure.js
My `node` executable happens to be a wrapper created by 0install, implemented in python. It relies on some library code being available on `$PYTHONPATH`. Which means it can't run when `npm-gyp` overwrites `$PYTHONPATH` to include _only_ the bundled `gyp/pylib` dir.
This commit achieves the same effect as the existing code (giving the bundled `gyp` module priority), but without clobbering an existing `$PYTHONPATH` value.
> configure: don't clobber existing $PYTHONPATH

- lib/configure.js
> Fixed #526. Check for python2 executable by default, fallback to python

- addon.gypi
Adds the name of the current target as a preprocessor define. Uses the automatic variable `_target_name` in combination with late variable expansion.
It originates in joyent/node#8802 but has other applications, too. Think logging. It's a little service to downstream add-ons to keep things DRY.
> Add target name preprocessor define

- package.json
@isaacs merged a PR that removed the built artifacts for browsers, which is a breaking version, so everything using semver needs to be updated to allow the new major version. It's a low-risk change, because there are no other changes to the package.
> allow semver@5

- README.md
- bin/node-gyp.js
- lib/install.js
- lib/node-gyp.js
- package.json
The project was moved from https://github.com/TooTallNate/node-gyp to
https://github.com/nodejs/node-gyp.  Update a handful of links that
still pointed to the old location.
R=@thefourtheye?
> Update repository URLs.

- lib/node-gyp.js
- test/test-options.js
The bundled copy of GYP enters an infinite loop when it encounters a
zero-length option so ensure those don't get through.
The root cause is a bad guard in gyp/pylib/gyp/input.py that doesn't
take into account that `'' in 'whatever'` evaluates to True.
Fixes: https://github.com/nodejs/node-gyp/issues/744
R=@rvagg
> Fix infinite loop with zero-length options.

- test/test-options.js
`npm test` dumps a ton of npm_config_* variables in the environment.
Remove those before starting the actual test.
R=@rvagg?
> Fix test/test-options when run through `npm test`.

- gyp/AUTHORS
- gyp/pylib/gyp/common.py
- gyp/pylib/gyp/generator/analyzer.py
- gyp/pylib/gyp/generator/cmake.py
- gyp/pylib/gyp/generator/make.py
- gyp/pylib/gyp/generator/ninja.py
- gyp/pylib/gyp/generator/xcode.py
- gyp/pylib/gyp/input.py
- gyp/pylib/gyp/xcode_emulation.py
- gyp/pylib/gyp/xcodeproj_file.py
* adds netbsd support: https://codereview.chromium.org/1421073004
* fixes cp(1) use on openbsd: https://codereview.chromium.org/1483473002
Fixes: https://github.com/nodejs/node-gyp/issues/571
Fixes: https://github.com/nodejs/node-gyp/pull/803
R=@rvagg?
> Upgrade gyp to b3cef02.

- gyp/pylib/gyp/generator/make.py
Gyp defaults to gcc/g++ if CC.host/CXX.host is unset. This is not
suitable for environments that only uses the clang toolchain.
Since we already assume that the user will provide clang/clang++
through CC/CXX, lean against it (then drop to gcc/g++).
Refs: https://github.com/nodejs/node/pull/6173
/cc @jbergstroem
> gyp: inherit CC/CXX for CC/CXX.host

- addon.gypi
- src/win_delay_load_hook.cc
Visual Studio 2015 Update 3 defines __pfnDliNotifyHook2 as const.
Fixes: https://github.com/nodejs/node-gyp/issues/949
> win: work around __pfnDliNotifyHook2 type change

- addon.gypi
We were inheriting BUILDING_UV_SHARED and BUILDING_V8_SHARED from
the common.gypi from the node.js source tree.  Override them with
USING_UV_SHARED and USING_V8_SHARED so symbols get tagged with
`__declspec(dllimport)` instead of `__declspec(dllexport)`, which
is the desired attribute when building add-ons.
Fixes: https://github.com/nodejs/node-gyp/issues/914
> Override BUILDING_UV_SHARED, BUILDING_V8_SHARED.

- README.md
- bin/node-gyp.js
- lib/node-gyp.js
Overrides the location where node-gyp will look for (and download to)
the node.js SDK.
For harmonization with the --nodedir flag, `osenv.home()` is now used
instead of `process.env.HOME || process.env.USERPROFILE`.
`osenv.home()` defaults to the built-in `os.homedir()` when available
and falls back to sane defaults based on the platform.
`%USERPROFILE%` is now preferred on Windows and `%HOME%` is ignored;
similarly, UNIX systems ignore `$USERPROFILE` from now on.  Neither
behavior made much sense, IMO.
Fixes: https://github.com/nodejs/node-gyp/issues/21
> Add --devdir flag.

- lib/configure.js
- test/test-find-python.js
See https://github.com/nodejs/node-gyp/issues/987#issuecomment-231969392.  Add lots and lots of tests that verify all code paths.
R=@rvagg?
CI: https://ci.nodejs.org/view/All/job/nodegyp-test-commit/8/
> Try python launcher when stock python is python 3.

- package.json
Should fix reports of "TypeError: Cannot read property 'length' of
undefined" runtime exceptions where node-gyp uses a buggy version
of semver due to our overly broad accepted version range.
npm updated to semver@5.3.0 recently so we can too now and still
share the module with npm, keeping the download small.
Fixes: https://github.com/nodejs/node-gyp/issues/1094
CI: https://ci.nodejs.org/view/All/job/nodegyp-test-commit/35/
> Upgrade semver dependency.

- README.md
> doc: blorb about `npm_config_devdir`

- lib/Find-VS2017.cs
Fixes: https://github.com/nodejs/node-gyp/issues/1179
Personally I prefer #1178, but this is smaller.
> win: more robust parsing of SDK version

- lib/configure.js
If you're providing a path to a header tarball to install, you probably
want it to always be re-installed.
Fixes: https://github.com/nodejs/node-gyp/issues/1216
> configure: don't set ensure if tarball is set

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Give users reporting bugs a clearer idea of the info that will be helpful when reporting issues.
Refs: https://github.com/nodejs/node/tree/master/.github
Also points users towards module issue trackers first.
I have no idea if the windows info is correct (or whether `node-gyp` uses `cc` on all UNIX). Please correct.
The PR template should be updated if/when we get a CONTRIBUTING.md (tracked in https://github.com/nodejs/node-gyp/issues/881)
> doc: add github PR and Issue templates

- addon.gypi
- gyp/pylib/gyp/common.py
- gyp/pylib/gyp/generator/make.py
- gyp/pylib/gyp/generator/ninja.py
- lib/configure.js
- test/fixtures/test-charmap.py
* recognize a zos system
* use correct cp arguments for zos
* add zos compile options
* add zos makedep arguments
* use export file in link step on zos
> zos: support platform

- README.md
Updated the README with another way to install the C++ build tools on windows.
> Update README with another way to install on windows

- gyp/pylib/gyp/xcode_emulation.py
As node-gyp rebuild doesn't seem to need xcodebuild, we don't need to be printing the error every time GYP is run.
Refs: https://github.com/nodejs/node-gyp/pull/1057
Refs: https://chromium-review.googlesource.com/c/492046/
Refs: https://github.com/nodejs/node-gyp/issues/569
As the previous attempts haven't landed, I thought I'd aim for a minimal diff. This seems to remove all `node-gyp build` warnings during `npm install` of a native module, and errors from running configure in node core, although for some reason the first line in Node's built-in gyp [uses `xcrun` rather than `xcodebuild`](https://github.com/nodejs/node/blob/8803b69c724e7b03ec0fc4c82b71575262487624/tools/gyp/pylib/gyp/xcode_emulation.py#L498).
This is caused by me running a "getting started with node" course, and having …
> gyp: don't print xcodebuild not found errors

- README.md
- Changed occurrences of "Mac OS X" to "macOS" as per Apple's recent rebranding
- Added information about `xcode-select --install` (an alternative to downloading developer tools from the Xcode UI)
- Deleted duplicate macOS build information from the Windows section of the README
Fixes #1295
> doc: update macOS information in README

- README.md
Fixes grammar, removes extra lines and spaces, etc. Also removes a few
references to `node-waf`, which was removed ~6 years ago now. Happy to
add back if people still need that information.
cc docs guru @Trott
> doc: lint README.md

- bin/node-gyp.js
- lib/build.js
- lib/clean.js
- lib/configure.js
- lib/find-node-directory.js
- lib/find-vs2017.js
- lib/install.js
- lib/list.js
- lib/node-gyp.js
- lib/process-release.js
- lib/rebuild.js
- lib/remove.js
- Removes "module dependencies" comments and things that, IMHO, don't add
too much value. Happy to add back if helps some people when reading
through `node-gyp`.
- DRY up `lib/process-release.js`.
- Removes a bunch of extra blank lines, as well as random spaces.
> bin,lib: remove extra comments/lines/spaces

- .eslintrc.yaml
- bin/node-gyp.js
- lib/build.js
- lib/configure.js
- lib/install.js
- lib/list.js
- lib/node-gyp.js
- lib/remove.js
- package.json
- test/test-configure-python.js
- test/test-find-accessible-sync.js
- test/test-find-python.js
Adds the `no-unused-vars` ESLint rule. Can add `npm run lint` to `nodegyp-test-commit` if people would like that.
> Add ESLint no-unused-vars rule

- gyp/PRESUBMIT.py
- gyp/pylib/gyp/MSVSSettings.py
- gyp/pylib/gyp/MSVSUserFile.py
- gyp/pylib/gyp/MSVSUtil.py
- gyp/pylib/gyp/MSVSVersion.py
- gyp/pylib/gyp/__init__.py
- gyp/pylib/gyp/easy_xml.py
- gyp/pylib/gyp/generator/analyzer.py
- gyp/pylib/gyp/generator/android.py
- gyp/pylib/gyp/generator/cmake.py
- gyp/pylib/gyp/generator/gypd.py
- gyp/pylib/gyp/generator/make.py
- gyp/pylib/gyp/generator/msvs.py
- gyp/pylib/gyp/generator/ninja.py
- gyp/pylib/gyp/generator/xcode.py
- gyp/pylib/gyp/input.py
- gyp/pylib/gyp/input_test.py
- gyp/pylib/gyp/mac_tool.py
- gyp/pylib/gyp/msvs_emulation.py
- gyp/pylib/gyp/ordered_dict.py
- gyp/pylib/gyp/simple_copy.py
- gyp/pylib/gyp/win_tool.py
- gyp/pylib/gyp/xcode_emulation.py
- gyp/pylib/gyp/xcode_ninja.py
- gyp/pylib/gyp/xcodeproj_file.py
- gyp/tools/graphviz.py
- gyp/tools/pretty_gyp.py
- gyp/tools/pretty_sln.py
- gyp/tools/pretty_vcproj.py
This doesn't fully port node-gyp to Python 3,
but it provides some fixes which bring it in the direction which makes
doing a full port to Python 3 easier.
> Add some Python 3 fixes to node-gyp

- gyp/pylib/gyp/mac_tool.py
In the current code __e__ is both undefined and unused so this code will raise an NameError exception which masks the original exception.
An alternative solution would be: __except Exception as e:__ but that still creates an unused variable.
> except e: --> except Exception:

- gyp/pylib/gyp/generator/make.py
- gyp/pylib/gyp/mac_tool.py
target is an undefined name in this context.
> target --> self.target

- README.md
- bin/node-gyp.js
- lib/configure.js
- lib/install.js
- package.json
Closes #175 and #1124. Besides changes to follow the XDG standard I took the liberty to:
- Fix a small current linter issue.
- Replace the `osenv` dependency with native `os` to decrease the amount of dependencies.
- Add a package lock.
Since `os.userInfo()` requires Node.js 6 or higher and the default data location is changed this would be a major version bump. I did not go for moving the old locations or falling back because it adds unneeded complexity not worth the trouble.
> Follow XDG OS conventions for storing data

- lib/configure.js
This fixes an issue introduced by commit https://github.com/nodejs/node-gyp/commit/da5db4059f9d3628a9fcace262c482d585460002 specifically this line https://github.com/nodejs/node-gyp/commit/da5db4059f9d3628a9fcace262c482d585460002#diff-7ad6309831a48a234780b58baca65710R440
Namely, the bit that checks for python versions was changed and went from supporting both python2 and python3 to supporting only python2.
I understand there are other open issues/PRs in regards to python3 but this change specifically is a regression that broke windows builders with python3 in the path as python.
> lib: use print() for python version detection

- addon.gypi
To solve the problem of linking a compiled module against a preinstalled library of termux-app on android I added a special condition branch to add the required -fPIC flag for the c and c++ compiler. After that everything compiled, linked and works as expected.
> Fix: module compilation within termux-app on android

- addon.gypi
- src/win_delay_load_hook.cc
- test/test-addon.js
Electron, starting with major version 4, ships a `node.lib` import library referencing `electron.exe` (`node` is statically linked) so it is no longer possible to freely rename `electron.exe` and have native modules work out of the box.
Is `node-gyp` interested in a change like this? or is this be something that the Electron team should work around themselves?
> win: fix delay-load hook for electron 4

- README.md
There must be some kind of separation there in the Readme. It isn't clear this isn't part of the Windows installation information.
> Python info needs own header

- lib/build.js
If node-gyp configure has set up MSBuild location use it instead the one that happens to be first on the PATH.
Fixes: https://github.com/nodejs/node-gyp/issues/1653
> win: use msbuild from the configure stage

- test/node_modules/hello_world/hello.cc
V8 7.4 removes some API functions. Replace those with their NAN
counterparts.
Example current failure: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1781/nodes=debian9-64/testReport/junit/(root)/citgm/node_gyp_v3_8_0/
```console
undefinedadded 121 packages from 83 contributors and audited 228 packages in 5.603s
found 0 vulnerabilities
> node-gyp@3.8.0 test /home/iojs/build/workspace/citgm-smoker/nodes/debian9-64/citgm_tmp/98118c6b-7f61-4357-abfd-24950d89737d/node-gyp
> tape test/test-*
TAP version 13
not ok 1 should be equal
---
operator: equal
expected: |-
null
actual: |-
{ [Error: Command failed: /home/iojs/build/workspace/citgm-smoker/nodes/debian9-64/smoker/bin/node /home/iojs/build/workspace/citgm-smoker/nodes/debian9-64/citgm_tmp/98118c6b-7f61-4357-abfd-24950d89737d/node- …
```
> test: fix addon test for Node.js 12 and V8 7.4

- .eslintrc.yaml
- .jshintrc
- bin/node-gyp.js
- lib/build.js
- lib/clean.js
- lib/configure.js
- lib/find-node-directory.js
- lib/find-visualstudio.js
- lib/install.js
- lib/list.js
- lib/node-gyp.js
- lib/process-release.js
- lib/rebuild.js
- lib/remove.js
- lib/util.js
- package.json
- test/process-exec-sync.js
- test/simple-proxy.js
- test/test-addon.js
- test/test-configure-python.js
- test/test-download.js
- test/test-find-accessible-sync.js
- test/test-find-node-directory.js
- test/test-find-python.js
- test/test-find-visualstudio.js
- test/test-install.js
- test/test-options.js
- test/test-process-release.js
IMO it's time for some proper linting, the code style is all over the place and the existing rules were super minimal. Current style is pretty close to standard.js, and it's a fairly universally accepted and understood style.
I've done a couple of additional things on top:
* moved `module.exports` to the bottom
* no single-line `if` statements
* no `if` statements without a `{`
* `const` for requires
This is going to make it harder to manage older pull requests of course, so this comes with a cost.
Thoughts?
> src: implement standard.js linting

- gyp/pylib/gyp/MSVSVersion.py
- gyp/pylib/gyp/generator/eclipse.py
- gyp/pylib/gyp/generator/msvs.py
- gyp/pylib/gyp/input.py
- gyp/pylib/gyp/mac_tool.py
- gyp/pylib/gyp/msvs_emulation.py
- gyp/pylib/gyp/win_tool.py
Fixes: #1943
Like #1890 and #1894 but for all remaining instances of popen.communicate() in this repo.  This conditionally decodes the bytes that come from popen.communicate() into str for proper handling in Python 3.
`grep -r communicate .` and ensure all stdout and stderr instances are decoded on Python 3.
> Finish decode stdout on Python 3

- gyp/pylib/gyp/xcode_emulation.py
Fixes: #1917
Recent changes have resulted in improper encoding of versions in the `XcodeVersion()` function.
This PR is meant to streamline the logic and properly encode versions that have single digit as well as double digit major versions.
> Fix TypeError in XcodeVersion()

- .github/workflows/Python_tests.yml
@joaocgreis This might be of interest to you.
> test: GitHub Actions add Windows to the testing

- README.md
- macOS_Catalina.md
The fixes suggested in macOS_Catalina.md are not working reliably in the latest versions of Catalina. @rrrix found that installing the Command Line Tools from dmg rather than xcode-select --install does work. This was confirmed by two other people, including myself.
> doc: update macOS_Catalina.md

- CHANGELOG.md
- package.json
* [[`aaf33c3029`](https://github.com/nodejs/node-gyp/commit/aaf33c3029)] - **build**: add update-gyp script (Samuel Attard) [#2167](https://github.com/nodejs/node-gyp/pull/2167)
* [[`3baa4e4172`](https://github.com/nodejs/node-gyp/commit/3baa4e4172)] - **(SEMVER-MINOR)** **gyp**: update gyp to 0.4.0 (Samuel Attard) [#2165](https://github.com/nodejs/node-gyp/pull/2165)
* [[`f461d56c53`](https://github.com/nodejs/node-gyp/commit/f461d56c53)] - **(SEMVER-MINOR)** **build**: support apple silicon (arm64 darwin) builds (Samuel Attard) [#2165](https://github.com/nodejs/node-gyp/pull/2165)
* [[`ee6fa7d3bc`](https://github.com/nodejs/node-gyp/commit/ee6fa7d3bc)] - **docs**: note that node-gyp@7 should solve Catalina CLT issues (Rod Vagg) [#2156](https://github.com/nodejs/node-gyp/pull/2156)
* …
> Release proposal: v7.1.0

- .github/workflows/tests.yml
From python: [3.6, 3.7, 3.8] --> python: [3.6, 3.8, 3.9] because if things work on Python 3.6 and 3.8 then they should work on 3.7.
https://www.python.org/downloads/release/python-390/
> GitHub Actions: Test on Python 3.9

- package.json
this is actually pretty simple, the two semver-major jumps are just dropping support for node 6, not introducing anything else that might break
> deps: update deps to match npm@7

- CHANGELOG.md
- package.json
This is the changelog, with a novel notice that we don't normally include:
v7.1.1 2020-10-15
=================
This release restores the location of shared library builds to the pre-v7
location. In v7.0.0 until this release, shared library outputs were placed
in a lib.target subdirectory inside the build/{Release,Debug} directory for
builds using `make` (Linux, etc.). This is inconsistent with macOS (Xcode)
behavior and previous node-gyp behavior so has been reverted.
We consider this a bug-fix rather than semver-major change.
* [[`ee6a837cb7`](https://github.com/nodejs/node-gyp/commit/ee6a837cb7)] - **gyp**: update gyp to 0.6.1 (Rod Vagg) [#2238](https://github.com/nodejs/node-gyp/pull/2238)
* [[`3e7f8ccafc`](https://github.com/nodejs/node-gyp/commit/3e7f8ccafc)] - **lib**: better log …
> v7.1.1 proposal

- .github/workflows/tests.yml
Fixes #2231 
Ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.
> ci: migrate deprecated grammar

- README.md
https://github.com/nodejs/node-gyp/pull/2277 - consistency now?
https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf - will add icon to copy
> doc: updated README.md to copy easily

- gyp/CHANGELOG.md
- gyp/pylib/gyp/generator/cmake.py
- gyp/pylib/gyp/generator/msvs.py
- gyp/pylib/gyp/input.py
- gyp/pylib/gyp/xcode_emulation.py
- gyp/setup.py
* **msvs:** On Windows, arguments passed to the "action" commands are no longer transformed to replace slashes with backslashes.
* **xcode:** --cross-compiling overrides arch-specific settings ([973bae0](https://www.github.com/nodejs/gyp-next/commit/973bae0b7b08be7b680ecae9565fbd04b3e0787d))
* **msvs:** do not fix paths in action command arguments ([fc22f83](https://www.github.com/nodejs/gyp-next/commit/fc22f8335e2016da4aae4f4233074bd651d2faea))
* cmake on python 3 ([fd61f5f](https://www.github.com/nodejs/gyp-next/commit/fd61f5faa5275ec8fc98e3c7868c0dd46f109540))
* ValueError: invalid mode: 'rU' while trying to load binding.gyp ([d0504e6](https://www.github.com/nodejs/gyp-next/commit/d0504e6700ce48f44957a4d5891b142a60be946f))
* xcode cmake parsing …
> gyp: update gyp to v0.7.0

- lib/configure.js
It is deprecated and will emit a warning in Node.js 16.
Refs: https://github.com/nodejs/node/pull/36902
> lib: avoid changing process.config

- README.md
- gyp/pylib/gyp/MSVSSettings.py
- gyp/pylib/gyp/generator/android.py
- test/fixtures/test-charmap.py
Ironic that #2300 is about the migration from 2 --> 3 ;-)
Roughly corresponds with nodejs/node#36691 and ~nodejs/gyp-next#88~
~Blocked by #2318~
Python 2 died one year ago so let's only support the currently supported versions of CPython:
https://devguide.python.org/#status-of-python-branches
Removes `windows-build-tools` because its current release unfortunately still installs legacy Python.
felixrieseberg/windows-build-tools#206
> gyp: remove support for Python 2

- .github/workflows/tests.yml
- gyp/pylib/gyp/generator/msvs.py
- test/fixtures/test-charmap.py
- update-gyp.py
This adds many more flake8 linting tests to align with `gyp-next`.  This PR ran ` black ./test/fixtures/test-charmap.py ./update-gyp.py` to format those files to align with https://github.com/psf/black formatting.
> Improve our flake8 linting tests

- gyp/.github/workflows/node-gyp.yml
- gyp/.github/workflows/release-please.yml
- gyp/CHANGELOG.md
- gyp/gyp_main.py
- gyp/pylib/gyp/MSVSSettings.py
- gyp/pylib/gyp/MSVSSettings_test.py
- gyp/pylib/gyp/__init__.py
- gyp/pylib/gyp/common_test.py
- gyp/pylib/gyp/easy_xml_test.py
- gyp/pylib/gyp/flock_tool.py
- gyp/pylib/gyp/generator/android.py
- gyp/pylib/gyp/generator/msvs_test.py
- gyp/pylib/gyp/generator/ninja_test.py
- gyp/pylib/gyp/generator/xcode_test.py
- gyp/pylib/gyp/input_test.py
- gyp/pylib/gyp/mac_tool.py
- gyp/pylib/gyp/win_tool.py
- gyp/setup.py
- gyp/test_gyp.py
- gyp/tools/graphviz.py
- gyp/tools/pretty_gyp.py
- gyp/tools/pretty_sln.py
- gyp/tools/pretty_vcproj.py
Ran `./update-gyp.py v0.8.1` to pull in `gyp` from `gyp-next` v0.8.1
- See the CHANGELOG: https://github.com/nodejs/gyp-next/releases/tag/v0.8.1
- and see the commit-for-commit comparison: https://github.com/nodejs/gyp-next/compare/v0.8.0...v0.8.1
In terms of actual source code changes, this is strictly updating the shebang lines of various Python source code files from `#!/usr/bin/env python` to `#!/usr/bin/env python3`... and a couple of functionally identical whitespace/indentation changes. (Other changes are version updates to GitHub actions in workflows for that repository, and a new entry in `gyp`'s `CHANGELOG.md` -- not functionally impactful to `node-gyp`.)
Partially addresses https://github.com/nodejs/node-gyp/issues/2351. (Addresses https://github.com/nodejs/node-gyp/issues/2351 …
> gyp: update gyp to v0.8.1

- CHANGELOG.md
- package.json
I think this needs a dep update. If someone would like to help out on that - go look at https://github.com/npm/cli/blob/latest/package.json and try and match the overlapping semver specifiers to theirs. I tend to keep them roughly in sync to avoid duplication in their releases. Whether or not they'll take a v8.0.0 is another matter, and we may want to recommend they hold off for a little while until this is tested in the wild.
* [[`15a5c7d45b`](https://github.com/nodejs/node-gyp/commit/15a5c7d45b)] - **ci**: migrate deprecated grammar (#2285) (Jiawen Geng) [#2285](https://github.com/nodejs/node-gyp/pull/2285)
* [[`cc1cbce056`](https://github.com/nodejs/node-gyp/commit/cc1cbce056)] - **doc**: update macOS\_Catalina.md (#2293) (iMrLopez) [#2293](https://github.com/nodejs/node-gyp/pull/2293) …
> Release proposal: v8.0.0

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release-please.yml
- CHANGELOG.md
Adds [`release-please-action`](https://github.com/google-github-actions/release-please-action) to this repository. `release-please-action` automatically creates/updates release proposal PRs when there are new commits on a given branch of the repository (currently configured as `master`). If the release proposal PR is merged, `release-please-action` will publish a corresponding entry in GitHub Releases, and add the new git tag for that version to the repository.
@gengjiawen and I added various NodeJS-style commit prefixes to be recognized in addition to the usual `chore:`, `fix:`, and `feat:` prefixes defined in [Conventional Commits](https://www.conventionalcommits.org). (Conventional Commits is the commit message spec `release-please` is based around.) These (and any arbitrary) prefixes …
> meta: add `release-please-action` for automated releases

- lib/configure.js
When logging `"build" dir needed to be created?`, put "Yes" or "No" instead of `[path that was created]` or `undefined` .
<details>
There is a bit of verbose logging in the package that informs the user whether the build dir needed to be created (as opposed to having already been there from a previous `node-gyp configure` run).
This bit of logging apparently expected to be given a boolean, but was receiving either a path or `undefined` based on the result of [`fs.mkdir()`](https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fs_mkdir_path_options_callback). So it was logging either the path of the build dir that was just created or `undefined`, somewhat nonsensically if you don't know what's going on behind the scenes.
Now it prints either "Yes" or "No".
Before:
`gyp verb build dir "build" …
> lib: log as yes/no whether build dir was created

- gyp/.github/workflows/release-please.yml
- gyp/CHANGELOG.md
- gyp/CODE_OF_CONDUCT.md
- gyp/CONTRIBUTING.md
- gyp/pylib/gyp/generator/make.py
- gyp/pylib/gyp/generator/ninja.py
- gyp/pylib/gyp/xcodeproj_file.py
- gyp/setup.py
- gyp/tools/emacs/gyp-tests.el
- gyp/tools/emacs/gyp.el
* use LDFLAGS_host for host toolset ([#98](https://www.github.com/nodejs/gyp-next/issues/98)) ([bea5c7b](https://www.github.com/nodejs/gyp-next/commit/bea5c7bd67d6ad32acbdce79767a5481c70675a2))
* msvs.py: remove overindentation ([#102](https://www.github.com/nodejs/gyp-next/issues/102)) ([3f83e99](https://www.github.com/nodejs/gyp-next/commit/3f83e99056d004d9579ceb786e06b624ddc36529))
* update gyp.el to change case to cl-case ([#93](https://www.github.com/nodejs/gyp-next/issues/93)) ([13d5b66](https://www.github.com/nodejs/gyp-next/commit/13d5b66aab35985af9c2fb1174fdc6e1c1407ecc))
> gyp: update gyp to v0.9.1

- lib/configure.js
In `lib/configure.js`, when creating the local `config` object as a copy of `process.config`, use `JSON.parse(JSON.stringify(process.config)` rather than `Object.assign({}, process.config)`.
Makes it so we won't modify properties of child objects of the original `process.config`. (Modifying `process.config` or its children is deprecated as of Node 16.)
<details><summary>Background</summary>
Testing with the latest Node v16 nightly build revealed that the deprecation warning from https://github.com/nodejs/node/pull/36902 was still showing with the latest `node-gyp` v8.0.0 during the  `config` or `rebuild` commands.
```
// ...
gyp info find Python using Python version 3.9.0 found at "/usr/local/bin/python3"
(node:21174) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In …
```
> lib: deep-copy process.config during configure

- lib/find-python.js
> Update wrong catch block

- CHANGELOG.md
- lib/find-visualstudio.js
https://github.com/codespell-project/codespell
> chore: fix typos discovered by codespell

- .github/workflows/tests.yml
Tracks with https://nodejs.org/en/about/releases
Also removes duplicate push and pull_requests tests.
> ci: GitHub Actions Test on node: [12.x, 14.x, 16.x]

- docs/Updating-npm-bundled-node-gyp.md
https://github.com/nodejs/node-gyp/issues/2272
> fix: doc how to update node-gyp independently from npm

- README.md
correct link to "binding.gyp files out in the wild"
doc: correct link to "binding.gyp files out in the wild" in README.md
> doc: correct README.md

- gyp/.github/workflows/Python_tests.yml
- gyp/.github/workflows/node-gyp.yml
- gyp/CHANGELOG.md
- gyp/pylib/gyp/MSVSUtil.py
- gyp/pylib/gyp/common.py
- gyp/pylib/gyp/easy_xml.py
- gyp/pylib/gyp/generator/android.py
- gyp/pylib/gyp/generator/make.py
- gyp/pylib/gyp/generator/msvs.py
- gyp/pylib/gyp/generator/ninja.py
- gyp/pylib/gyp/input.py
- gyp/pylib/gyp/msvs_emulation.py
- gyp/pylib/gyp/win_tool.py
- gyp/pylib/gyp/xcodeproj_file.py
- gyp/setup.py
- gyp/test_gyp.py
> feat(gyp): update gyp to v0.9.6

- README.md
- lib/configure.js
- lib/create-config-gypi.js
- lib/node-gyp.js
- test/fixtures/nodedir/include/node/config.gypi
- test/test-configure-python.js
- test/test-create-config-gypi.js
Close https://github.com/nodejs/node-gyp/issues/2490.
This PR makes the generated `config.gypi` file inherit from `$nodedir/include/node/config.gypi` instead of runtime's `process.config` object when `--nodedir` or `--dist-url` is passed. There is also a `--force-process-config` flag added to force switching back to the old behavior. For the reason behind this change, please check https://github.com/nodejs/node-gyp/issues/2490.
This change should have not affect to Node.js users, since they usually don't use either `--nodedir` or `--dist-url`. And even when they explicitly do so, since the `process.config` is generated from the `$nodedir/include/node/config.gypi`, the build configurations will be exactly the same.
For users building modules for Electron, this is a breaking change because …
> feat: build with config.gypi from node headers

- package.json
This updates `npmlog` to the latest version. It will also clear all current `npm audit` warnings for any project that has this package installed.
The semver-major change in npmlog@5 was dropping support for node 6 and 8.
The semver-major change in npmlog@6 was dropping support for node10, and non-LTS versions of node12 and node14 (i.e. `<12.13.0` and `<14.15.0`)
I don't believe either of those are issues for the current version of node-gyp.
> deps: npmlog@6.0.0

- docs/Force-npm-to-use-global-node-gyp.md
- docs/Updating-npm-bundled-node-gyp.md
Fix issue https://github.com/nodejs/node-gyp/issues/2573
> fix(docs): title match content

- docs/Force-npm-to-use-global-node-gyp.md
- docs/Updating-npm-bundled-node-gyp.md
Add notes on npm version compatibility for methods to update the copy of node-gyp that npm uses.
Also mention that this is tested on npm 8, now that npm 8 exists. (Npm 8 is the same as npm 7 for purposes of these instructions.)
Lastly, add a note that one of the methods is simpler/more durable, but only functional for npm 6 and older.
> docs: Add notes/disclaimers for upgrading the copy of node-gyp that npm uses

- README.md
* Add Python 3.10
* Drop Python 3.6 which [EOLs on 23 Dec. 2021](https://devguide.python.org/#status-of-python-branches)
* macOS: clarify `Xcode Command Line Tools` standalone vs. from full Xcode
* Windows: Use the same URL as https://github.com/nodejs/node/blob/master/BUILDING.md#windows
> doc: Update Python versions

- package.json
Makes npm warn users if they are using an unsupported Node version.
Commit message follows the pattern from the last time this field was updated: https://github.com/nodejs/node-gyp/pull/2153
> deps: increase "engines" to "node" : "^12.22 || ^14.13 || >=16"

- package.json
This updates the `make-fetch-happen` dependency from `^9.1.0` to `^10.0.1`.
The breaking change was dropping node10 support, which node-gyp has
already done.
> deps: make-fetch-happen@10.0.1

- package.json
The sporadic timeouts seen here were caused by a change to the default `freeSocketTimeout` value in the `agentkeepalive` module. To work around the issue, we've increased the value back to its original default. This change is only to ensure that the minimum required version of `make-fetch-happen` is one that has this fix applied.
> fix: update make-fetch-happen to a minimum of 10.0.3

- lib/create-config-gypi.js
- lib/node-gyp.js
- test/test-options.js
This PR fixes 2 things on `npm_config_` env variables:
1. Make `npm_config_force_process_config=true` env work by automatically converting `_` to `-` when parsing `npmConfigPrefix`.
2. Recognize `--disturl` as option in `create-config-gypi.js`, it is not documented anywhere but users have been relying on `npm_config_disturl` to pass `--dist-url` in env.
> fix: _ in npm_config_ env variables

- lib/configure.js
Required to enable node.js to build shared library on z/OS.
> lib: add lib.target as path for searching libnode on z/OS

- lib/build.js
- lib/configure.js
- test/test-configure-python.js
An attempt to fix https://github.com/nodejs/node-gyp/issues/2351 for the rest of users not yet addressed by https://github.com/nodejs/node-gyp/pull/2355.
- Symlink the valid Python binary found by `lib/find-python.js` at `build/node_gyp_bins/python3`
- Add `build/node_gyp_bins` to the `PATH` just before building
- Ensures any of the build-time Python scripts (such as `build/gyp-mac-tool` or `build/gyp-flock-tool`) will be run with the Python binary validated by`lib/find-python.js`
**The corner case/bug is not applicable to Windows. So this PR changes nothing on Windows.**
<details>
This PR changes nothing on Windows. The bug being fixed is Not Applicable to Windows; There are no Python scripts to run at build time on Windows, per my testing, nor as far as I can deduce from research.
_(If …
> Add Python symlink to path (for non-Windows OSes only)

- README.md
Clarifies that macOS_Catalina.md is meant for any user that's upgraded beyond 10.15 and not just users that upgraded to 10.15 Catalina
> fix: wording to redirect to macOS_Catalina.md

- lib/find-visualstudio.js
fix: Fixes #2527
Latest Windows 11 SDK was not supported by implementation due to a change in the naming convention made by Microsoft. The implementation has been amended to account for this change.
> feat: Update function getSDK() to support Windows 11 SDK

- lib/configure.js
[zoslib](https://github.com/ibmruntimes/zoslib) is needed to support node.js on z/OS
> lib: enable support for zoslib on z/OS

- package.json
Updates the `nopt` dependency to `6.0.0`
No functional changes, just dropping old node versions from engines,
linting, and fixing CI.
> deps: nopt@6.0.0

- gyp/pylib/gyp/input.py
Debugger attached.
Waiting for the debugger to disconnect...
> fix: node.js debugger adds stderr (but exit code is 0) -> shouldn't throw

- update-gyp.py
From https://github.com/nodejs/node/pull/44823:
> # Patching CVE-2007-4559
> 
> Hi, we are security researchers from the Advanced Research Center at [Trellix](https://www.trellix.com). We have began a campaign to patch a widespread bug named CVE-2007-4559. CVE-2007-4559 is a 15 year old bug in the Python tarfile package. By using extract() or extractall() on a tarfile object without sanitizing input, a maliciously crafted .tar file could perform a directory path traversal attack. We found at least one unsantized extractall() in your codebase and are providing a patch for you via pull request. The patch essentially checks to see if all tarfile members will be extracted safely and throws an exception otherwise. We encourage you to use this patch or your own solution to secure against …
> Adding tarfile member sanitization to extractall()

- addon.gypi
Open XL C/C++ for z/OS (C invocation: clang, ibm-clang64 or ibm-clang) is LLVM-based, and doesn't support XL C/C++'s -q flags. Environment variable CC is set starting with Node.js v18 for z/OS which requires clang compiler, but CC may not be set in older versions (which required njsc or xlclang).
> feat: support IBM Open XL C/C++ on z/OS

- lib/find-visualstudio.js
Refs: https://github.com/nodejs/node/issues/37472
> feat: remove support for VS2015 in Node.js >=19

- .github/workflows/tests.yml
Python 3.6 is no longer supported: https://devguide.python.org/versions. This PR drops it from the CI test matrix.
This PR replaces #2772 which was an alternative solution to fix the CI failures that resulted from this.
> ci: update python test matrix

- .github/workflows/tests.yml
- gyp/pylib/gyp/generator/eclipse.py
- gyp/pylib/gyp/xcodeproj_file.py
[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) including bandit, isort, pylint, pyupgrade, and flake8 plus its plugins and is written in Rust for speed.
The `ruff` Action uses minimal steps to run in ~10 seconds, rapidly providing intuitive GitHub Annotations to contributors.
@nodejs/python
> feat: Upgrade Python linting from flake8 to ruff

- .github/workflows/tests.yml
- update-gyp.py
`numeric_owner` is a keyword-only argument in Python v3.9. When I try running the script without the change, Python gives me the following error:
```
Unzipping...
Traceback (most recent call last):
File "C:\Users\raymondzhao\work\node-gyp\update-gyp.py", line 54, in <module>
safe_extract(tar_ref, unzip_target)
File "C:\Users\raymondzhao\work\node-gyp\update-gyp.py", line 52, in safe_extract
tar.extractall(path, members, numeric_owner)
TypeError: extractall() takes from 1 to 3 positional arguments but 4 were given
```
> chore: get update-gyp.py to work with Python >= v3.5

- package.json
Closes #2795
Blocked by #2770
http-cache-semantics 4.1.0 is vulnerable
https://www.cve.org/CVERecord?id=CVE-2022-25881
http-cache-semantics 4.1.0 is vulnerable
https://www.cve.org/CVERecord?id=CVE-2022-25881
https://github.com/npm/make-fetch-happen/pull/210
> update make-fetch-happen to 11.0.3

- package.json
- test/reporter.js
- test/test-addon.js
- test/test-configure-python.js
- test/test-create-config-gypi.js
- test/test-download.js
- test/test-find-accessible-sync.js
- test/test-find-node-directory.js
- test/test-find-python.js
- test/test-find-visualstudio.js
- test/test-install.js
- test/test-options.js
- test/test-process-release.js
After the `make-fetch-happen` update in https://github.com/nodejs/node-gyp/commit/02480f6b6894a6bb81dd3e1365bc4df6d5336f7c, GitHub Actions started failing. Migrating from `tap` to `mocha` testing framework as issues only happened in GitHub Actions (tested locally with various node/python combinations, didn't reproduce any failures). This PR is made based on investigation and work done in https://github.com/nodejs/node-gyp/pull/2837 as the simplest and probably the cleanest solution. With these changes, `Mocha` replaces `tap` completely, thus restoring GitHub Actions stability.
> Migration from tap to mocha

- lib/install.js
Updating this log statement to be accurate.
> fix: log statement is for devDir not nodedir

- lib/install.js
- package.json
- test/test-download.js
Instead of downloading node.lib for all architectures, just download the one that will be needed. `install.js` changed to enable downloading just node.lib for node versions that already have tarball downloaded and extracted. Not fetching lib now fails the installation. Increased installVersion because of the changes.
A note to reviewers - although it seems there are many changes, most of them are just indentation. Also @dsanders11 I'd like to ask you for a review, since your change for `install.js` landed a few days ago, and I worked on those parts of the code too.
Refs: https://github.com/nodejs/node-gyp/issues/2847
> win,install: only download target_arch node.lib

- .github/workflows/tests.yml
Since Node.js v14 has reached its EOL, this PR removes it from GitHub Actions for testing.
> test: remove deprecated Node.js and Python

- lib/find-python.js
These changes favor the py launcher check over other checks excluding command line or npm configuration and environment variable checks on Windows
Also, updated supported Python versions list.
Fixes: https://github.com/nodejs/node-gyp/issues/2871
> lib: find python checks order changed on windows

- lib/configure.js
- lib/node-gyp.js
- test/test-options.js
Ever since #2547 went in for version 9 our Windows machines can't properly read msvs_version from the .npmrc. Since names with '_' are now changed to '-' we need to change the opts definition. If there's a different way you'd like to handle this let me know and I can update.
> Fix reading msvs version on Windows

- README.md
Update readme for windows installation. Fixes #2637
> docs: Update windows installation instructions in README.md

- gyp/pylib/gyp/generator/make.py
> fix: a Python lint error by using an f-string

- package.json
Since migrating from Tap to Mocha it can be observed that sometimes tests will fail on Windows because of the "after all" hook is not executed within 2 seconds. This change increases the default timeout affecting that hook in order to avoid failures due to this hook timing out.
> test: increase mocha timeout

- CHANGELOG.md
Add an entry for PR https://github.com/nodejs/node-gyp/pull/2362 to the CHANGELOG.md for version 9.1.0.
(Details below...)
---
PR https://github.com/nodejs/node-gyp/pull/2362 was merged without a prefixed name, such as "lib:" or "fix:". That means `release-please` didn't include it in the changelog for v9.1.0.
This change did end up affecting users, though. (See issue https://github.com/nodejs/node-gyp/issues/2713 and PR https://github.com/nodejs/node-gyp/pull/2721). Therefore, I believe PR https://github.com/nodejs/node-gyp/pull/2362 should be noted in the CHANGELOG.md, so users can better understand the behavior they are seeing.
(And of course, I think a fix for the unintended side-effects of https://github.com/nodejs/node-gyp/pull/2362 should be merged soon if reasonably possible. See: …
> doc: Add note about Python symlinks (PR 2362) to CHANGELOG.md for v9.1.0

- .github/workflows/release-please.yml
- .github/workflows/tests.yml
- .github/workflows/visual-studio.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs/README.md
Mostly just tidying up the links (which for now redirect), but changing the branch for the workflow status badge in `README.md` fixes it - it was still pointing at `master` and so it wasn't accurately reflecting the current state of `main` (it currently says passing, even though it's failing).
> docs: update applicable GitHub links from master to main

- .github/scripts/check-engines.js
- .github/workflows/tests.yml
- package.json
This will test against regressions in (sub-)dependency engine changes and guard against breaking changes like #2848 #2873.
Errors will look like this:
```
Error: The following production dependencies are not compatible with `engines.node: ^14.17.0 || ^16.13.0 || >=18.0.0` found in `/home/runner/work/node-gyp/node-gyp/package.json`:
make-fetch-happen@13.0.0:
engines.node: ^16.14.0 || >=18.0.0
location: node_modules/make-fetch-happen
which@4.0.0:
engines.node: ^16.13.0 || >=18.0.0
location: node_modules/which
```
> chore: add check engines script to CI

- lib/configure.js
- lib/find-python.js
- lib/find-visualstudio.js
- lib/node-gyp.js
- test/common.js
- test/test-find-python.js
- test/test-find-visualstudio.js
> [!NOTE]
> This PR is stacked on #2924
BREAKING CHANGE: the `Gyp` class exported is now created using
ECMAScript classes and therefore might have small differences to classes
that were previously created with `util.inherits`.
> feat: convert internal classes from util.inherits to classes

- lib/configure.js
The `findAccessibleSync()` function is in the local `util` module instead of Node.js' builtin `util` module.
Refs: https://github.com/nodejs/node/pull/50493#issuecomment-1790806476
---
Existing tests should cover this, but only on AIX or z/OS, neither of which are available on GitHub Actions (and neither of those OSes are a supported platform for running a self-hosted runner).
> fix: use local `util` for `findAccessibleSync()`

- CHANGELOG.md
This PR is related to issue https://github.com/nodejs/node-gyp/issues/2937 and removes
- update engines.node to ^14.17.0 || ^16.13.0 || >=18.0.0
from the [CHANGELOG](https://github.com/nodejs/node-gyp/blob/main/CHANGELOG.md) which is outdated and contradicts the previous correct line which states:
- node-gyp now supports node ^16.14.0 || >=18.0.0
~~To complete the resolution of issue https://github.com/nodejs/node-gyp/issues/2937, the release notes [node-gyp v10.0.0](https://github.com/nodejs/node-gyp/releases/tag/v10.0.0) need to be separately edited.~~ Edit: Done
> docs: remove outdated update engines.node reference in 10.0.0 changelog

- .github/workflows/release-please.yml
https://github.com/nodejs/node-gyp/commit/3032e1061cc2b7b49f83c397d385bafddc6b0214 added `pull_request` to `release-please.yml`. This was necessary to get CI running after a release PR was created since a push by CI will not run other actions.
This updates it further so the `release-please` portion only runs on `push`, and then the post release tests run on either 1) a successful release or 2) a PR where the head ref starts with `release-v`
> chore: only run release please on push

- README.md
Refs: https://github.com/nodejs/node-gyp/issues/2953
Readme contains outdated Node versions which may be misleading for some users. Replaced specific versions with more abstract 'current and lts versions'.
> docs: remove outdated Node versions from readme

- README.md
Helped refine the readme text to improve clarity and readability
> refine readme Visual C++ Build Environment text for clarity

- docs/Updating-npm-bundled-node-gyp.md
> Updating-npm-bundled-node-gyp.md: npm is currently v10

- lib/configure.js
- test/test-configure-nodedir.js
- test/test-configure-python.js
Some linux distros allow headers to be installed through tools like rpm. If the runtime sets
process.config.variables.use_prefix_to_find_headers, look for matching headers based on the directory set for the prefix in process.config.variables.prefix
> src: add support for locally installed headers

- README.md
- lib/find-visualstudio.js
- test/fixtures/VSSetup_VS_2019_Professional_workload.txt
- test/fixtures/VSSetup_VS_2022_VS2019_workload.txt
- test/fixtures/VSSetup_VS_2022_multiple_install.txt
- test/fixtures/VSSetup_VS_2022_workload.txt
- test/fixtures/VSSetup_VS_2022_workload_missing_sdk.txt
- test/test-find-visualstudio.js
Detect visual studio installation using VSSetup module and Get-VSSetupInstance method as a first attempt, this approach works even in systems with Constrained language mode of the powershell. 
Original type-base detection requires `FullLanguage` mode, which quite often not available on the enrolled devices.
> Detect visual studio installation using VSSetup module 

- lib/find-visualstudio.js
- test/test-find-visualstudio.js
Since Node.js v22 will use C++20 standard, VS2017 can no longer be used for compiling native add-ons. This is already changed in [the docs](https://github.com/nodejs/build/blob/main/doc/windows-visualstudio-supported-versions.md#for-building-nodejs-addons). This PR drop VS2017 support for Node.js v22 and above for node-gyp.
**Note:** Node-gyp with this change should be released and consumed by Node for the v22 RC to avoid potential problems on Windows.
cc @targos, @nodejs/node-gyp
Refs: https://github.com/nodejs/build/pull/3603
Refs: https://github.com/nodejs/node/pull/45427
> win: update supported vs versions

- lib/find-python.js
- test/test-find-python.js
The Python executable path may have non-ASCII characters, which can make the print function fail if the environment encoding is different. This PR fixes this issue by using `stdout.buffer`, which can be used with UTF-8 encoding for the output, regardless of the environment encoding.
Fixes: https://github.com/nodejs/node-gyp/issues/2829
Refs: https://github.com/nodejs/node-gyp/pull/2987
> lib: print Python executable path using UTF-8

- README.md
We are getting a lot of issues opened on this topic so add this notice to our installation instructions.
> [!Important]
> Python >= v3.12 requires `node-gyp` >= v10
Related to:
* #2869
Uses [GitHub Markdown alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts):
> README.md: Installation -- Python >= v3.12 requires `node-gyp` >= v10

- README.md
Closes https://github.com/nodejs/node-gyp/issues/2636
Update the documentation for Node-Gyp installation on Windows by adding a guide for using Chocolatey to simplify the installation of the required dependencies for the node-gyp. The proposed guide simplifies the process by providing a one-liner command to install the necessary dependencies, namely `Python` and `Visual Studio 2022 workload for C++` tools
> Add Chocolatey Guide for node-gyp on Windows

- .github/workflows/tests.yml
- test/test-find-visualstudio.js
Fixes #2993
`npm test` is running and **failing** Windows `find-visualstudio` tests on an M1 Mac!!!
These tests are either not being run or are not failing on Intel Macs.
GitHub Actions blog:
> Over the next 12 weeks, jobs using the `macos-latest` runner label will migrate from macOS 12 (Monterey) to macOS 14 (Sonoma).
https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image
Discovered by @GeoffreyPlitt in:
* #2992
* #2993
@jarig
> GitHub Actions: npm test is failing Windows tests on M1 Macs

- docs/README.md
`npm config set msvs_version 2022` is no longer accepted on modern versions on `npm`.
@GeoffreyPlitt Please see the workaround.
> docs: `node-pre-gyp` is no longer maintained

- .github/workflows/release-please.yml
The release-please action URL was recently changed from https://github.com/google-github-actions/release-please-action to https://github.com/googleapis/release-please-action (see https://github.com/googleapis/release-please-action/issues/980). This fixes the release-please action.
> fix(ci): use correct release-please-action domain after organization url was changed

- .github/workflows/tests.yml
> cross-env NODE_GYP_NULL_LOGGER=true mocha --timeout 15000 test/test-download.js test/test-*
>
> sh: cross-env: command not found
> chore(ci) test on Node.js v22 and not v16

- lib/create-config-gypi.js
This PR is opened based on https://github.com/nodejs/node/pull/55784 as it is required to enable running native (addon) tests for the ClangCL-produced binaries on Windows. The original PR is reviewed and approved in the Node.js repo and I'm moving to the next phase now - landing the changes in their respective repositories. Node-gyp is the only dependency that needs changing outside Node.js, so I've decided to start with it.
> feat: prohibit compiling with ClangCL on Windows

- .github/workflows/release-please.yml
- .github/workflows/tests.yml
The `npm-publish` steps depends on output variable `release-please.outputs.release_created`. Without this variable the steps are skipped, e.g. https://github.com/nodejs/node-gyp/actions/runs/12087642317.
---
Adds npm provenance statements: https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow.
---
The release-please bot created PR needs an additional token to trigger CI runs: 
>    When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
>    https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
Removing the always …
> chore: fix npm-publish dependencies and add provenance

- eslint.config.js
- package.json
This is built on #3102.
After updating those dependencies, `standard` was the only dep bringing in anything deprecated. I read https://github.com/standard/standard/issues/1948#issuecomment-2138078249 and opted to migrate to `neostandard` following the instructions here: https://github.com/neostandard/neostandard?tab=readme-ov-file#migrate-from-standard
> chore: migrate from standard to neostandard

- src/win_delay_load_hook.cc
It is a following PR of https://github.com/nodejs/node/issues/47682.
I've tried to rename my executable to `node.exe` but the error is still there.
That's because the node.js's symbol is in `libnode.dll` but not in my executable. So, `GetModuleHandle(NULL)` will not work.
However, I think we can try to load `libnode.dll` first. If failed then fallback to try the executable. That will solve the problem and keep the original path work either.
Maybe it is looks like a edge case, but as Node.js has a [embedding tutorial](https://nodejs.org/dist/latest-v18.x/docs/api/embedding.html) in the doc, I think it's worth to do this.
Or please tell me if there is a more simple way to solve my problem.
------
Test is not included because I need to provide a huge nodedll binary.
Thank you, I love …
> try libnode.dll first in load_exe_hook

- .github/workflows/tests.yml
- .github/workflows/visual-studio.yml
- lib/find-visualstudio.js
https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info
https://learn.microsoft.com/en-us/windows-server/get-started/whats-new-windows-server-2025
* actions/runner-images#11228
Windows 2025 currently ships with Visual Studio 2022.
`vswhere -latest -property installationPath`
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise
```
> Test on GitHub Actions `windows-2025` image

- .github/workflows/release-please.yml
- .github/workflows/update-gyp-next.yml
- update-gyp.py
Add automated updater for gyp-next.
Example: https://github.com/legendecas/node-gyp/pull/1
> chore: add gyp-next updater

- .github/workflows/tests.yml
Fixes: #3119 
Blocked by: seanmiddleditch/gha-setup-ninja#31
Also:
* Windows tests are slow so let them run first
* Add Node.js v23 to the testing
* Use [seanmiddleditch/gha-setup-ninja@v6](https://github.com/seanmiddleditch/gha-setup-ninja/releases) for compatibility with Ubuntu on ARM
* [Detect operating system with runner.os](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#detecting-the-operating-system)
[Standard GitHub-hosted runners for public repositories](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) --> `os: ubuntu-24.04-arm`
@seanmiddleditch Your review, please.
> Test on Ubuntu-24.04-arm and Node.js v23

- lib/build.js
- package.json
https://npmgraph.js.org/?q=glob - 26 dependencies
https://npmgraph.js.org/?q=tinyglobby - 2 dependencies
> chore: switch to tinyglobby

- lib/build.js
- package.json
I forgot to add the `{ expandDirectories: false }` option to avoid matching directories named `.sln` or `.mk`. Better to add it to be safe...
> chore: update tinyglobby

- .github/workflows/tests.yml
- test/test-windows-make.js
fixes https://github.com/nodejs/node-gyp/issues/3144
> test: fix wasm test on Windows

- src/win_delay_load_hook.cc
Based on the description in the linked issue, this should fix the problem. There is no strong reason for making a change like this (and for example not using `GetModuleHandleA` or `L"libnode.dll"`). This is the only `GetModuleHandle` call in the entire project, so if someone thinks other approaches are better, let me know and I'll change it.
Fixes: https://github.com/nodejs/node-gyp/issues/3126
Refs: https://github.com/nodejs/node-gyp/pull/2834
> win,src: fix GetModuleHandle for libnode.dll

- docs/README.md
Add a caution about `ffi-napi` to `docs/README.md`.  https://github.com/nodejs/node-gyp/issues?q=label%3Affi-napi
* * node-ffi-napi/node-ffi-napi#269
Also, remove a similar caution about `node-pre-gyp` which is now properly maintained.
Massive thanks to @benmccann for leading the modernization of  `node-pre-gyp`.  🏆 🚀 
* https://github.com/mapbox/node-pre-gyp/releases
@addaleax
> fix: add a caution about ffi-napi to docs/README.md

- lib/build.js
On windows, one may experience errors due to concurrent node-gyp calls (see #3095)
When retrying after such a failure, retries are observed to fail repeatedly with strange
EBUSY and EPERM errors. This turns out to be due to a caching feature where msbuild.exe
will continue to run in the background (for either 15s or 15m depending on VS version),
and keep open file handles to files and directories that the user may be trying to delete
(for example with a new call to `npm ci`).
This behavior is [well](https://stackoverflow.com/questions/51076195/why-is-msbuild-generating-tlog-files-into-cmakefiles-compileridc-and-how-do-i) [documented](https://github.com/dotnet/msbuild/issues/1709), as is the [recommended workaround](https://learn.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/tr …
> fix: disable msbuild.exe nodeReuse

- lib/build.js
- lib/clean.js
- lib/install.js
- lib/remove.js
on some linux machines, i observed:
```
npm error gyp http fetch GET https://artifacts.electronjs.org/headers/v30.5.1/node-v30.5.1-headers.tar.gz?force_headers_dist=1 attempt 1 failed with ETIMEDOUT
npm error gyp WARN install got an error, rolling back install
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: ENOTEMPTY: directory not empty, rmdir '/home/AzDevOps/.cache/node-gyp/30.5.1/include/node'
```
(side note: i'm not sure why the http fetch is not being retried, or where the "attempt 1" comes from)
unfortunately this leaves the system in a broken state, as a subsequent retries (with my own loop around npm) all fail:
```
npm failed 1, trying again...
...
npm error gyp WARN read config.gypi ENOENT: no such file or directory, open …
```
> fix: remove more forcefully

- test/test-download.js
- test/test-install.js
This might help with flaky tests like #3113 did for the source code.
> test: use maxRetries with tests too

- .github/workflows/tests.yml
Downloading `wasi-sdk` was failing intermittently in CI with the following error:
```
Start-BitsTransfer: D:\a\_temp\2d842915-cf29-4e19-ad5c-0579032af0fb.ps1:2
Line |
2 |  Start-BitsTransfer -Source https://github.com/WebAssembly/wasi-sdk/re …
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The connection with the server was terminated abnormally 
Error: Process completed with exit code 1.
```
[Ref to CI run](https://github.com/nodejs/node-gyp/actions/runs/14196147703/job/39771631687?pr=3135#step:6:16)
This PR retries the download 3 times since I've only seen this error be transient so far.
> chore: retry wasi-sdk download in CI

- addon.gypi
I ran into this cross-compiling on a case-sensitive file-system. The official sdk includes this file:
`VC/Tools/MSVC/14.44.35207/lib/x64/delayimp.lib`
which does not have any casing. For simplicity, its easiest to list libraries with lower case names.
> Normalize win32 library names

- lib/install.js
> fix: use temp dir for tar extraction on all platforms

- .github/workflows/tests.yml
https://docs.astral.sh/ruff/rules/import-outside-top-level
There are several valid reasons for conditionally importing Python modules, especially for OS-specific code, so let's intentionally ignore this rule.
% `ruff check --select=PLC0415`
```
Error: gyp/pylib/gyp/MSVSVersion.py:222:5: PLC0415 `import` should be at the top-level of a file
Error: gyp/pylib/gyp/__init__.py:492:9: PLC0415 `import` should be at the top-level of a file
Error: gyp/pylib/gyp/generator/make.py:81:9: PLC0415 `import` should be at the top-level of a file
Error: gyp/pylib/gyp/generator/ninja.py:1998:9: PLC0415 `import` should be at the top-level of a file
Error: gyp/pylib/gyp/generator/ninja.py:2021:9: PLC0415 `import` should be at the top-level of a file
Error: gyp/pylib/gyp/generator/ninja.py:2091:9: PLC0415 …
```
> Lint Python: Ignore ruff rule PLC0415

- README.md
- lib/node-gyp.js
- test/test-options.js
`npm@11` has deprecated setting arbitrary config values (https://github.com/npm/cli/issues/8153), which was the previously recommended place for users to set node-gyp related config. The new recommendation from npm is to use the `config` object in package.json for this (https://github.com/npm/cli/issues/8153#issuecomment-2718937461). I think it makes sense to follow npm's recommendation here.
When a user sets a value in `package.json#config` it will be set in the environment by npm with the prefix `npm_package_config_<KEY>`.
I think it makes sense to allow prescribe that they keys be prefixed with `node_gyp_`. So as an example:
**package.json**
```json
{
"config": {
"node_gyp_devdir": "/tmp/.gyp"
}
}
```
Then in `node-gyp` we can read the env var `npm_package_config_node_gyp_devdir`. If a …
> feat: support reading config from package.json

- lib/node-gyp.js
- test/test-options.js
This is a follow-up to #3196. As a user I'd be confused if `npm_package_config_node_gyp_devdir` worked but `NPM_PACKAGE_CONFIG_NODE_GYP_DEVDIR` did not. Especially because previously `npm` would read them as case insensitive as well.
> feat: read from config case-insensitively

- .github/workflows/release-please.yml
OIDC is only supported in npm >=11.5.1.
Fixes #3201
> chore(release): use npm@11 for publishing

- addon.gypi
When I build the addon on the OpenHarmony operating system, I encounter errors related to linker parameters.
For example, this is the error log I encountered when building [bufferutil](https://www.npmjs.com/package/bufferutil).
```log
npm error code 1
npm error path /data/test0826/node_modules/bufferutil
npm error command failed
npm error command sh -c node-gyp-build
npm error make: Entering directory '/data/test0826/node_modules/bufferutil/build'
npm error   CC(target) Release/obj.target/bufferutil/src/bufferutil.o
npm error   SOLINK_MODULE(target) Release/obj.target/bufferutil.node
npm error make: Leaving directory '/data/test0826/node_modules/bufferutil/build'
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@11.2.0
npm error gyp info using node@24.2.0 | …
```
> build: add adaptation for OpenHarmony platform

- .github/workflows/tests.yml
- test/fixtures/test-charmap.py
- update-gyp.py
Format Python code with ruff format: https://docs.astral.sh/ruff/formatter
* Add formatting to GitHub Actions -- `ruff format --check --diff`
> chore: ruff format Python code

- .github/workflows/tests.yml
Python v3.14 -- October 7th
* https://www.python.org/download/pre-releases
* https://www.python.org/downloads/release/python-3140rc3
Node.js using Python 3.14 on Windows is blocked by:
* nodejs/node#59983
---
Also, upgrade from deprecated `macos-13` to `macos-15-intel`.
The currently available GitHub Actions macOS runners are:
| macOS Version | runner.arch |
|---------------|-------------|
| macos-13 | X64 |
| macos-14 | ARM64 |
| macos-15 | ARM64 |
| macos-15-intel | X64 |
| macos-26 | ARM64 |
| macos-latest | ARM64 |
* Let's prepare for actions/runner-images#13046
> fix(ci): Test on Python 3.14 release candidate 3 on Linux and macOS
