- lib/install.js
This makes issues like #623 easier to debug
> Show URL when a download fails

- README.md
> Update readme for visual studio 2013

- lib/install.js
Spelling fix: "dowloading" should be "dow**n**loading".
> Fix download error message spelling

- README.md
> Updated Installation section on README

- README.md
Feature exists but is not documented.
> readme: document --jobs max

- test/test-download.js
I missed this when reviewing https://github.com/nodejs/node-gyp/pull/1796.
> test: fix typo in header download test

- README.md
preview here https://github.com/nodejs/node-gyp/blob/rvagg/github-actions-readme/README.md
> doc: add GitHub Actions badge

- macOS_Catalina.md
Updated download link for Command Line Tools for Xcode from v11.3 to v11.3.1.
> Update macOS Catalina docs

- README.md
Refs: https://github.com/nodejs/node-gyp/issues/2071
> doc: note in README that Python 3.8 is supported

- macOS_Catalina.md
> Add cmd to reset `xcode-select` to initial state

- CHANGELOG.md
- package.json
* [[`096e3aded5`](https://github.com/nodejs/node-gyp/commit/096e3aded5)] - **gyp**: update gyp to 0.6.2 (Myles Borins) [#2241](https://github.com/nodejs/node-gyp/pull/2241)
* [[`54f97cd243`](https://github.com/nodejs/node-gyp/commit/54f97cd243)] - **doc**: add cmd to reset `xcode-select` to initial state (Valera Rozuvan) [#2235](https://github.com/nodejs/node-gyp/pull/2235)
> v7.1.1 release proposal

- macOS_Catalina.md
Just added a link to the installation page so the Catalina users get to the command faster
> doc: update macOS_Catalina.md

- .github/workflows/tests.yml
https://github.com/actions/setup-node/releases
As the title says.
> ci: update actions/setup-node to v2

- README.md
> doc: add downloads badge

- README.md
Changed the URL to the Visual Studio Community installer from a default polski URL to the one without the language code
> doc: Update README.md Visual Studio Community page polski to auto

- README.md
This link link to the latest visual studio community version.
> doc: remove redundant version info

- update-gyp.py
> fix: change default gyp update message

- docs/Updating-npm-bundled-node-gyp.md
> Add title to node-gyp version document

- .github/ISSUE_TEMPLATE.md
Also, add a caution about `node sass` being deprecated.
> ISSUE_TEMPLATE.md: Instructions for old versions

- .github/workflows/tests.yml
https://www.python.org/downloads
https://github.com/actions/python-versions/releases
Let's start testing to make sure that we are ready...
> test: Python 3.10 was release on Oct. 4th

- docs/Updating-npm-bundled-node-gyp.md
Fix a typo in the powershell node-gyp update command
> docs: fix typo in powershell node-gyp update

- docs/Updating-npm-bundled-node-gyp.md
> fix: windows command missing space

- SECURITY.md
> chore: add minimal SECURITY.md

- docs/binding.gyp-files-in-the-wild.md
> feat: added node-heapdump binding.gyp

- .github/workflows/tests.yml
https://github.com/actions/setup-node/releases
https://github.com/actions/setup-python/releases
> test: Upgrade GitHub Actions

- README.md
Just fix little typo related to #2592 @cclauss
> fix: typo on readme

- macOS_Catalina.md
Follow-on to #2495
Fixes https://github.com/nodejs/node-gyp/issues/1927#issuecomment-1162532730
> Migrate macOS acid test from master to main

- .github/workflows/visual-studio.yml
Try testing on all MSVS_VERSIONs available in the GitHub Actions runner.
* https://github.com/actions/virtual-environments/tree/main/images/win
NOTE: I am not a Windows person so I might be doing this all wrong. ;-)
It is unclear to me what `GYP_MSVS_OVERRIDE_PATH=C:\\Dummy' >> $Env:GITHUB_ENV` does.
How can we ___prove___ that `MSVS_VERSION` is being used in the testing?
> test: Try msvs-version: [2016, 2019, 2022]

- docs/README.md
> Improved advise on repacing node-sass with sass

- docs/README.md
> docs: docs/README.md add advise about deprecated node-sass

- README.md
> Fix incorrect Xcode casing in README

- .github/workflows/release-please.yml
> Revert "build(deps): bump google-github-actions/release-please-action from 2 to 4"

- gyp/pylib/gyp/generator/android.py
- gyp/pylib/gyp/generator/gypsh.py
- gyp/pylib/gyp/generator/msvs.py
- gyp/pylib/gyp/input.py
- gyp/pylib/gyp/msvs_emulation.py
- gyp/pyproject.toml
https://docs.astral.sh/ruff/rules/f-string
% `ruff check --select=UP032 --fix`
* nodejs/gyp-next#234
* https://github.com/astral-sh/ruff/releases
> Fix lint: ruff check --select=UP032 --fix

- README.md
> fix README: add the way to configuring Python dependency for Windows PowerShell

- .github/workflows/tests.yml
GitHub Action is failing for `ruff` command updates: https://github.com/nodejs/node-gyp/actions/runs/9859674689/job/27223992436.
> chore: fix ruff command

- CODE_OF_CONDUCT.md
> Added code of conduct to project

- .github/workflows/release-please.yml
Add npm publish step after release-release.
> chore: publish to npm with release-please

- .github/workflows/tests.yml
> chore: Use astral-sh/ruff-action@v3 to run the Python linter

- .github/workflows/visual-studio.yml
Fixes typo in Visual Studio test matrix
> fix: Correct Visual Studio 2019 test version

- .github/workflows/visual-studio.yml
> chore: Windows 2019 has been removed from GitHub Actions

- .github/workflows/tests.yml
> chore(ci): Update Node.js version matrix in `tests.yml`

- .github/workflows/visual-studio.yml
Run our GitHub Actions test for Visual Studio on Windows 11 ARM
* https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
* https://github.com/actions/partner-runner-images/blob/main/images/arm-windows-11-image.md#visual-studio-enterprise-2022
* https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview
> fix(ci): Run Visual Studio test on Windows 11 on ARM
